In [1]:
!pip3 install torch

In [0]:
import torch

In [4]:
one_d = torch.arange(2,7)
one_d

tensor([2, 3, 4, 5, 6])

In [6]:
one_d = torch.arange(2,7,2)
one_d

tensor([2, 4, 6])

In [8]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
two_d = one_d.view(3,3)
two_d


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [12]:
two_d.dim()

2

In [15]:
two_d[0,0]

tensor(0)

In [16]:
two_d[1,2]

tensor(5)

In [18]:
x = torch.arange(18).view(2,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [19]:
x = torch.arange(18).view(3,3,2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])